OFFICIAL_RU_NEWS_SOURCES = [
    {
        "slug": "cbr-site-updates",
        "name": "Банк России: новое на сайте",
        "source_type": "rss",
        "base_url": "https://www.cbr.ru/rss/RssNews",
        "is_trusted": True,
        "reliability_score": 0.94,
        "config": {"language": "ru", "publisher": "cbr", "category": "site_updates"},
    },
    {
        "slug": "cbr-press",
        "name": "Банк России: пресс-релизы",
        "source_type": "rss",
        "base_url": "https://www.cbr.ru/rss/RssPress",
        "is_trusted": True,
        "reliability_score": 0.98,
        "config": {"language": "ru", "publisher": "cbr", "category": "press_release"},
    },
    {
        "slug": "cbr-events",
        "name": "Банк России: новости и выступления",
        "source_type": "rss",
        "base_url": "https://www.cbr.ru/rss/eventrss",
        "is_trusted": True,
        "reliability_score": 0.96,
        "config": {"language": "ru", "publisher": "cbr", "category": "news"},
    },
    {
        "slug": "moex-all-news",
        "name": "Московская биржа: все новости",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=100",
        "is_trusted": True,
        "is_active": False,
        "reliability_score": 0.78,
        "config": {"language": "ru", "publisher": "moex", "category": "all_news", "technical_feed": True},
    },
    {
        "slug": "moex-main-news",
        "name": "Московская биржа: главные новости",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=101",
        "is_trusted": True,
        "reliability_score": 0.94,
        "config": {"language": "ru", "publisher": "moex", "category": "top_news"},
    },
    {
        "slug": "moex-listing-news",
        "name": "Московская биржа: новости листинга",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=104",
        "is_trusted": True,
        "is_active": False,
        "reliability_score": 0.78,
        "config": {"language": "ru", "publisher": "moex", "category": "listing", "technical_feed": True},
    },
    {
        "slug": "moex-risk-params",
        "name": "Московская биржа: риск-параметры",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=122",
        "is_trusted": True,
        "is_active": False,
        "reliability_score": 0.76,
        "config": {"language": "ru", "publisher": "moex", "category": "risk_params", "technical_feed": True},
    },
    {
        "slug": "moex-ir-news",
        "name": "Московская биржа: investor relations",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=207",
        "is_trusted": True,
        "reliability_score": 0.93,
        "config": {
            "language": "ru",
            "publisher": "moex",
            "category": "investor_relations",
        },
    },
    {
        "slug": "moex-fx-news",
        "name": "Московская биржа: валютный рынок",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=210",
        "is_trusted": True,
        "reliability_score": 0.9,
        "config": {
            "language": "ru",
            "publisher": "moex",
            "category": "fx_news",
        },
    },
    {
        "slug": "moex-it-news",
        "name": "Московская биржа: IT-новости",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=209",
        "is_trusted": True,
        "reliability_score": 0.82,
        "config": {"language": "ru", "publisher": "moex", "category": "it_news"},
    },
    {
        "slug": "moex-indices-news",
        "name": "Московская биржа: индексы",
        "source_type": "rss",
        "base_url": "https://www.moex.com/export/news.aspx?cat=206",
        "is_trusted": True,
        "reliability_score": 0.8,
        "config": {"language": "ru", "publisher": "moex", "category": "indices"},
    },
    {
        "slug": "moex-dividends-api",
        "name": "MOEX ISS: дивиденды по бумагам",
        "source_type": "api",
        "base_url": "https://iss.moex.com/iss/securities/{symbol}/dividends.json?iss.meta=off",
        "is_trusted": True,
        "reliability_score": 0.88,
        "config": {
            "language": "ru",
            "publisher": "moex",
            "category": "corporate_events",
            "parser": "moex_dividends_api",
            "min_year": 2025,
        },
    },
    {
        "slug": "newsapi-finance",
        "name": "NewsAPI: finance search",
        "source_type": "api",
        "base_url": "https://newsapi.org/v2/everything",
        "is_active": False,
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {
            "language": "ru",
            "publisher": "newsapi",
            "category": "finance",
            "parser": "newsapi",
            "query": 'финансы OR акции OR биржа OR "Банк России" OR MOEX',
            "page_size": 50,
        },
    },
    {
        "slug": "finnhub-market-news",
        "name": "Finnhub: market news",
        "source_type": "api",
        "base_url": "https://finnhub.io/api/v1/news",
        "is_active": False,
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {
            "language": "en",
            "publisher": "finnhub",
            "category": "market",
            "parser": "finnhub_market_news",
        },
    },
    {
        "slug": "alpha-vantage-news-sentiment",
        "name": "Alpha Vantage: News & Sentiment",
        "source_type": "api",
        "base_url": "https://www.alphavantage.co/query",
        "is_active": False,
        "is_trusted": False,
        "reliability_score": 0.74,
        "config": {
            "language": "en",
            "publisher": "alpha_vantage",
            "category": "finance",
            "parser": "alpha_vantage_news_sentiment",
            "topics": "financial_markets,economy_macro",
            "limit": 50,
        },
    },
    {
        "slug": "marketaux-financial-news",
        "name": "Marketaux: financial news",
        "source_type": "api",
        "base_url": "https://api.marketaux.com/v1/news/all",
        "is_active": False,
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {
            "language": "en",
            "publisher": "marketaux",
            "category": "finance",
            "parser": "marketaux",
            "countries": "us,gb,ru",
            "limit": 50,
        },
    },
    {
        "slug": "gnews-finance",
        "name": "GNews: finance search",
        "source_type": "api",
        "base_url": "https://gnews.io/api/v4/search",
        "is_active": False,
        "is_trusted": False,
        "reliability_score": 0.7,
        "config": {
            "language": "ru",
            "publisher": "gnews",
            "category": "finance",
            "parser": "gnews",
            "query": "финансы OR акции OR биржа OR рынок",
            "limit": 50,
        },
    },
    {
        "slug": "reuters-business-finance",
        "name": "Reuters: business and finance",
        "source_type": "rss",
        "base_url": "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
        "is_active": False,
        "is_trusted": True,
        "reliability_score": 0.9,
        "config": {"language": "en", "publisher": "reuters", "category": "business_finance"},
    },
    {
        "slug": "ft-home",
        "name": "Financial Times: latest",
        "source_type": "rss",
        "base_url": "https://www.ft.com/rss/home",
        "is_trusted": True,
        "reliability_score": 0.9,
        "config": {"language": "en", "publisher": "ft", "category": "finance"},
    },
    {
        "slug": "rbc-finance",
        "name": "РБК: финансы",
        "source_type": "rss",
        "base_url": "https://rssexport.rbc.ru/rbcnews/news/30/full.rss",
        "is_trusted": True,
        "reliability_score": 0.84,
        "config": {"language": "ru", "publisher": "rbc", "category": "finance"},
    },
    {
        "slug": "interfax-business",
        "name": "Интерфакс: бизнес",
        "source_type": "rss",
        "base_url": "https://www.interfax.ru/rss.asp",
        "is_trusted": True,
        "reliability_score": 0.9,
        "config": {"language": "ru", "publisher": "interfax", "category": "business"},
    },
    {
        "slug": "prime-economy",
        "name": "ПРАЙМ: экономика и рынки",
        "source_type": "rss",
        "base_url": "https://1prime.ru/export/rss2/index.xml",
        "is_trusted": True,
        "reliability_score": 0.88,
        "config": {"language": "ru", "publisher": "prime", "category": "economy"},
    },
    {
        "slug": "kommersant-news",
        "name": "Коммерсантъ: новости",
        "source_type": "rss",
        "base_url": "https://www.kommersant.ru/RSS/news.xml",
        "is_trusted": True,
        "reliability_score": 0.86,
        "config": {"language": "ru", "publisher": "kommersant", "category": "business"},
    },
    {
        "slug": "kommersant-business",
        "name": "Коммерсантъ: бизнес",
        "source_type": "rss",
        "base_url": "https://www.kommersant.ru/RSS/section-business.xml",
        "is_trusted": True,
        "reliability_score": 0.88,
        "config": {"language": "ru", "publisher": "kommersant", "category": "business"},
    },
    {
        "slug": "vedomosti-news",
        "name": "Ведомости: новости",
        "source_type": "rss",
        "base_url": "https://www.vedomosti.ru/rss/news",
        "is_trusted": True,
        "reliability_score": 0.86,
        "config": {"language": "ru", "publisher": "vedomosti", "category": "business"},
    },
    {
        "slug": "vedomosti-business",
        "name": "Ведомости: бизнес",
        "source_type": "rss",
        "base_url": "https://www.vedomosti.ru/rss/rubric/business",
        "is_trusted": True,
        "reliability_score": 0.88,
        "config": {"language": "ru", "publisher": "vedomosti", "category": "business"},
    },
    {
        "slug": "finmarket-news",
        "name": "Финмаркет: новости",
        "source_type": "rss",
        "base_url": "https://www.finmarket.ru/rss.asp",
        "is_trusted": True,
        "reliability_score": 0.86,
        "config": {"language": "ru", "publisher": "finmarket", "category": "finance"},
    },
    {
        "slug": "finmarket-main-news",
        "name": "Финмаркет: главные новости",
        "source_type": "rss",
        "base_url": "https://www.finmarket.ru/rss/mainnews.asp",
        "is_trusted": True,
        "reliability_score": 0.87,
        "config": {"language": "ru", "publisher": "finmarket", "category": "finance"},
    },
    {
        "slug": "finmarket-analytics",
        "name": "Финмаркет: аналитика",
        "source_type": "rss",
        "base_url": "https://www.finmarket.ru/rss/analytics.asp",
        "is_trusted": True,
        "reliability_score": 0.82,
        "config": {"language": "ru", "publisher": "finmarket", "category": "analytics"},
    },
    {
        "slug": "mfd-financial-news",
        "name": "MFD.RU: финансовые новости",
        "source_type": "rss",
        "base_url": "https://mfd.ru/rss/news/handler.ashx",
        "is_trusted": False,
        "reliability_score": 0.76,
        "config": {"language": "ru", "publisher": "mfd", "category": "finance"},
    },
    {
        "slug": "mfd-analyst-comments",
        "name": "MFD.RU: комментарии аналитиков",
        "source_type": "rss",
        "base_url": "https://mfd.ru/rss/comments/handler.ashx",
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {"language": "ru", "publisher": "mfd", "category": "analytics"},
    },
    {
        "slug": "lenta-economics",
        "name": "Lenta.ru: экономика",
        "source_type": "rss",
        "base_url": "https://lenta.ru/rss/news/economics/",
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {"language": "ru", "publisher": "lenta", "category": "economics"},
    },
    {
        "slug": "forbes-ru-news",
        "name": "Forbes Россия: новости",
        "source_type": "rss",
        "base_url": "https://www.forbes.ru/newrss.xml",
        "is_trusted": False,
        "reliability_score": 0.78,
        "config": {"language": "ru", "publisher": "forbes_ru", "category": "business"},
    },
    {
        "slug": "finam-news",
        "name": "Финам: новости рынка",
        "source_type": "rss",
        "base_url": "https://www.finam.ru/analysis/conews/rsspoint/",
        "is_trusted": False,
        "reliability_score": 0.76,
        "config": {"language": "ru", "publisher": "finam", "category": "market"},
    },
    {
        "slug": "smartlab-news",
        "name": "Smart-Lab: новости",
        "source_type": "rss",
        "base_url": "https://smart-lab.ru/news/rss/",
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {"language": "ru", "publisher": "smartlab", "category": "market"},
    },
    {
        "slug": "banki-news",
        "name": "Банки.ру: новости",
        "source_type": "rss",
        "base_url": "https://www.banki.ru/xml/news.rss",
        "is_trusted": False,
        "reliability_score": 0.74,
        "config": {"language": "ru", "publisher": "banki", "category": "finance"},
    },
    {
        "slug": "frank-media",
        "name": "Frank Media",
        "source_type": "rss",
        "base_url": "https://frankmedia.ru/feed",
        "is_trusted": False,
        "reliability_score": 0.74,
        "config": {"language": "ru", "publisher": "frank_media", "category": "finance"},
    },
    {
        "slug": "investing-ru-news",
        "name": "Investing.com Россия: новости",
        "source_type": "rss",
        "base_url": "https://ru.investing.com/rss/news.rss",
        "is_trusted": False,
        "reliability_score": 0.72,
        "config": {"language": "ru", "publisher": "investing_ru", "category": "market"},
    },
    {
        "slug": "tass-newswire",
        "name": "ТАСС: новостная лента",
        "source_type": "rss",
        "base_url": "https://tass.ru/rss/v2.xml",
        "is_trusted": True,
        "reliability_score": 0.82,
        "config": {"language": "ru", "publisher": "tass", "category": "newswire"},
    },
    {
        "slug": "ria-newswire",
        "name": "РИА Новости: новостная лента",
        "source_type": "rss",
        "base_url": "https://ria.ru/export/rss2/archive/index.xml",
        "is_trusted": True,
        "reliability_score": 0.8,
        "config": {"language": "ru", "publisher": "ria", "category": "newswire"},
    },
]
